-- MySQL Script generated by MySQL Workbench
-- чт, 02-бер-2017 11:00:16 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema university_library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university_library` DEFAULT CHARACTER SET utf8 ;
USE `university_library` ;

-- -----------------------------------------------------
-- Table `university_library`.`Reader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Reader` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(25) NOT NULL,
  `first_name` VARCHAR(25) NOT NULL,
  `middle_name` VARCHAR(25) NOT NULL,
  `priority` TINYINT NOT NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(20) NULL,
  `address_country` VARCHAR(45) NULL,
  `address_state` VARCHAR(45) NULL,
  `address_region` VARCHAR(45) NULL,
  `address_city` VARCHAR(45) NULL,
  `address_street` VARCHAR(45) NULL,
  `address_house` VARCHAR(45) NULL,
  `address_flat` VARCHAR(45) NULL,
  `address_zipcode` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_library`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reader_id` INT NOT NULL,
  `faculty` VARCHAR(50) NOT NULL,
  `group` VARCHAR(10) NOT NULL,
  `speciality_code` VARCHAR(30) NOT NULL,
  `speciality_title` VARCHAR(45) NOT NULL,
  `course` TINYINT NOT NULL,
  `start_date` DATE NOT NULL,
  `graduation_date` DATE NOT NULL,
  `education_form` VARCHAR(20) NOT NULL,
  `education_type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `reader_id_UNIQUE` (`reader_id` ASC),
  CONSTRAINT `student_reader_id`
    FOREIGN KEY (`reader_id`)
    REFERENCES `university_library`.`Reader` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_library`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Teacher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reader_id` INT NOT NULL,
  `faculty` VARCHAR(50) NOT NULL COMMENT '	',
  `departument` VARCHAR(50) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `degree` VARCHAR(20) NULL,
  `rank` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `reader_id_UNIQUE` (`reader_id` ASC),
  CONSTRAINT `teacher_reader_id`
    FOREIGN KEY (`reader_id`)
    REFERENCES `university_library`.`Reader` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_library`.`Postgraduate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Postgraduate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reader_id` INT NOT NULL,
  `speciality_code` VARCHAR(30) NOT NULL,
  `speciality_title` VARCHAR(45) NOT NULL,
  `faculty` VARCHAR(50) NULL,
  `education_type` VARCHAR(45) NOT NULL,
  `is_break_work` TINYINT(1) NULL,
  `start_date` DATE NOT NULL,
  `graduation_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `reader_id_UNIQUE` (`reader_id` ASC),
  CONSTRAINT `postgraduate_reader_id`
    FOREIGN KEY (`reader_id`)
    REFERENCES `university_library`.`Reader` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_library`.`Preparatory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Preparatory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reader_id` INT NOT NULL,
  `education_form` VARCHAR(20) NOT NULL,
  `start_studying` DATE NOT NULL,
  `end_studying` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `reader_id_UNIQUE` (`reader_id` ASC),
  CONSTRAINT `preparatory_reader_id`
    FOREIGN KEY (`reader_id`)
    REFERENCES `university_library`.`Reader` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_library`.`Applicant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Applicant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reader_id` INT NOT NULL,
  `education_level` VARCHAR(20) NOT NULL,
  `speciality_code` VARCHAR(30) NOT NULL,
  `speciality_title` VARCHAR(45) NOT NULL,
  `entry_year` YEAR NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `reader_id_UNIQUE` (`reader_id` ASC),
  CONSTRAINT `applicant_reader_id`
    FOREIGN KEY (`reader_id`)
    REFERENCES `university_library`.`Reader` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_library`.`Certification_Training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Certification_Training` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reader_id` INT NOT NULL,
  `start_training` DATE NOT NULL,
  `end_training` DATE NOT NULL,
  `departument` VARCHAR(50) NOT NULL,
  `speciality` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `reader_id_UNIQUE` (`reader_id` ASC),
  CONSTRAINT `certification_training_reader_id`
    FOREIGN KEY (`reader_id`)
    REFERENCES `university_library`.`Reader` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_library`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `city` VARCHAR(50) NULL,
  `publisher` VARCHAR(100) NULL,
  `series` VARCHAR(100) NULL,
  `year` YEAR NULL,
  `pages_count` INT NOT NULL,
  `days_keep_count` INT NOT NULL,
  `adding date` DATE NOT NULL,
  `periodic release` INT NULL,
  `count` INT NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_library`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `middle_name` VARCHAR(100) NULL,
  `pseudonym` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_library`.`Book_Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Book_Author` (
  `book_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `author_id`),
  INDEX `fk_Book_has_Author_Author1_idx` (`author_id` ASC),
  INDEX `fk_Book_has_Author_Book1_idx` (`book_id` ASC),
  CONSTRAINT `fk_Book_has_Author_Book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `university_library`.`Book` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Book_has_Author_Author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `university_library`.`Author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_library`.`Section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Section` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university_library`.`Book_Section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Book_Section` (
  `book_id` INT NOT NULL,
  `section_id` INT NOT NULL,
  `book_count` INT NOT NULL,
  PRIMARY KEY (`book_id`, `section_id`),
  INDEX `fk_Book_has_Section_Section1_idx` (`section_id` ASC),
  INDEX `fk_Book_has_Section_Book1_idx` (`book_id` ASC),
  CONSTRAINT `fk_Book_has_Section_Book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `university_library`.`Book` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Book_has_Section_Section1`
    FOREIGN KEY (`section_id`)
    REFERENCES `university_library`.`Section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_library`.`Book_Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_library`.`Book_Event` (
  `reader_id` INT NOT NULL,
  `section_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `order date` DATE NULL,
  `event_state` VARCHAR(45) NOT NULL,
  `violation` VARCHAR(45) NULL,
  `punishment` VARCHAR(45) NULL,
  `sanctions_period` TINYINT NULL,
  PRIMARY KEY (`reader_id`, `section_id`, `book_id`),
  INDEX `fk_Reader_has_Section_Section1_idx` (`section_id` ASC),
  INDEX `fk_Reader_has_Section_Reader1_idx` (`reader_id` ASC),
  INDEX `fk_Book_Event_Book1_idx` (`book_id` ASC),
  CONSTRAINT `fk_Reader_has_Section_Reader1`
    FOREIGN KEY (`reader_id`)
    REFERENCES `university_library`.`Reader` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Reader_has_Section_Section1`
    FOREIGN KEY (`section_id`)
    REFERENCES `university_library`.`Section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_Event_Book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `university_library`.`Book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;
